### ISSUE TITLE
DaggerAppComponent not found

### ISSUE THREAD

**Issue by hosseinkhojany** [LanguageXX/Simple-Notes-Kotlin-App#1]
in class BaseApplication DaggerAppComponent interface not found i think it is are AppComponent then how can change or edit it 

 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: james_gosling.projects.notepad_kotlin, PID: 4029
    java.lang.RuntimeException: Unable to start activity ComponentInfo{james_gosling.projects.notepad_kotlin/james_gosling.projects.notepad_kotlin.ui.MainActivity}: java.lang.RuntimeException: android.app.Application does not implement dagger.android.HasAndroidInjector
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3364)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3548)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7539)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
     Caused by: java.lang.RuntimeException: android.app.Application does not implement dagger.android.HasAndroidInjector
        at dagger.android.AndroidInjection.inject(AndroidInjection.java:49)
        at dagger.android.support.DaggerAppCompatActivity.onCreate(DaggerAppCompatActivity.java:41)
        at james_gosling.projects.notepad_kotlin.ui.MainActivity.onCreate(MainActivity.kt:17)
        at android.app.Activity.performCreate(Activity.java:7455)
        at android.app.Activity.performCreate(Activity.java:7445)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3343)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3548) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:7539) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958) 
2020-10-03 13:32:20.802 4453-4453/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: james_gosling.projects.notepad_kotlin, PID: 4453
    java.lang.RuntimeException: Unable to start activity ComponentInfo{james_gosling.projects.notepad_kotlin/james_gosling.projects.notepad_kotlin.ui.MainActivity}: java.lang.RuntimeException: android.app.Application does not implement dagger.android.HasAndroidInjector
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3364)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3548)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7539)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
     Caused by: java.lang.RuntimeException: android.app.Application does not implement dagger.android.HasAndroidInjector
        at dagger.android.AndroidInjection.inject(AndroidInjection.java:49)
        at dagger.android.support.DaggerAppCompatActivity.onCreate(DaggerAppCompatActivity.java:41)
        at james_gosling.projects.notepad_kotlin.ui.MainActivity.onCreate(MainActivity.kt:17)
        at android.app.Activity.performCreate(Activity.java:7455)
        at android.app.Activity.performCreate(Activity.java:7445)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3343)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3548) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:7539) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958) 
2020-10-03 13:33:03.354 4755-4755/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: james_gosling.projects.notepad_kotlin, PID: 4755
    java.lang.RuntimeException: Unable to start activity ComponentInfo{james_gosling.projects.notepad_kotlin/james_gosling.projects.notepad_kotlin.ui.MainActivity}: java.lang.RuntimeException: android.app.Application does not implement dagger.android.HasAndroidInjector
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3364)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3548)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7539)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
     Caused by: java.lang.RuntimeException: android.app.Application does not implement dagger.android.HasAndroidInjector
        at dagger.android.AndroidInjection.inject(AndroidInjection.java:49)
        at dagger.android.support.DaggerAppCompatActivity.onCreate(DaggerAppCompatActivity.java:41)
        at james_gosling.projects.notepad_kotlin.ui.MainActivity.onCreate(MainActivity.kt:17)
        at android.app.Activity.performCreate(Activity.java:7455)
        at android.app.Activity.performCreate(Activity.java:7445)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3343)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3548) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2155) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:7539) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958) 
2020-10-03 13:33:22.677 4860-4860/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: james_gosling.projects.notepad_kotlin, PID: 4860

i recive this error

**Comment by prakashshuklahub** [comment]
Build your project again and try to invalidate cache and restart
